name: ðŸž Bug Report
description: English template for reporting a bug
labels: [ "bug" ]

body:
  - type: input
    id: name
    attributes:
      label: Package Name
      description: name of package which has bug(s)
    validations:
      required: true

  - type: textarea
    id: related
    attributes:
      label: Current Behaviour | Expected Behaviour
      description: >-
        <br>For the description, assume we have no idea how packages work,
        be as detailed as possible and include a step by step reproduction.
        <br>It is recommended you try to reproduce the issue you are having yourself with as few steps as possible.
        <br>The clearer the description, the higher the report processing priority
      value: >-
        *Current Behaviour:*
        <br>
        *Expected Behaviour:*
        <br>
      render: 'raw'
    validations:
      required: true

  - type: textarea
    id: contexts
    attributes:
      label: Additional context/output
      description: 'Add any other context about the problem here. If applicable, paste terminal output here to help explain.'

  - type: textarea
    id: ps
    attributes:
      label: Possible Solution
